
module.exports = {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: 'chapter-1', // Generate sidebar slice from docs/chapter-1
    },    {
      type: 'autogenerated',
      dirName: 'chapter-2', // Generate sidebar slice from docs/chapter-2
    },    {
      type: 'autogenerated',
      dirName: 'chapter-3', // Generate sidebar slice from docs/chapter-3
    },    {
      type: 'autogenerated',
      dirName: 'chapter-4', // Generate sidebar slice from docs/chapter-4
    },    {
      type: 'autogenerated',
      dirName: 'chapter-5', // Generate sidebar slice from docs/chapter-5
    },  ],
};
