param(
    [int]$NumChapters = 5,
    [int]$NumLessonsPerChapter = 5
)

# Define paths
$docsDir = "website/docs"
$sidebarPath = "sidebar.js" # Assuming sidebar.js is in the root or accessible path

# Ensure docs directory exists
if (-not (Test-Path $docsDir)) {
    New-Item -ItemType Directory -Path $docsDir -Force | Out-Null
}

# Generate chapter and lesson structure
for ($c = 1; $c -le $NumChapters; $c++) {
    $chapterDir = Join-Path $docsDir "chapter-$c"
    if (-not (Test-Path $chapterDir)) {
        New-Item -ItemType Directory -Path $chapterDir -Force | Out-Null
    }

    # Create _category_.json
    $categoryContent = @"
{
  "label": "Chapter $c",
  "position": $c,
  "link": {
    "type": "generated-index",
    "description": "Lessons for Chapter $c"
  }
}
"@
    Set-Content -Path (Join-Path $chapterDir "_category_.json") -Value $categoryContent

    for ($l = 1; $l -le $NumLessonsPerChapter; $l++) {
        $lessonFileName = "lesson-$l.md"
        $lessonFilePath = Join-Path $chapterDir $lessonFileName

        # Pre-populate lesson file with constitution-defined sections
        $lessonContent = @"
---
title: Lesson $c.$l Title
sidebar_position: $l
---

## Description
A one-line description of Lesson $c.$l.

## Objectives
- Understand the primary objective of this lesson.
- Learn key concepts related to this lesson.

## Key Concepts
- Concept A
- Concept B

## Explanation
Detailed explanation of the lesson's topics.

## Example
A practical example demonstrating the concepts.

```
# Code or steps for the example
```

## Exercise
1. Question 1
2. Question 2
"@
        Set-Content -Path $lessonFilePath -Value $lessonContent
    }
}

# Update sidebar.js
# This part is more complex as it involves modifying an existing JS file.
# For simplicity, we'll generate a basic sidebar structure, assuming a fresh setup.
# In a real-world scenario, you might need to parse and modify an existing sidebar.js
# This assumes that the sidebar is not dynamically generated, but is a fixed file.

$sidebarContent = "
module.exports = {
  mySidebar: [
"
for ($c = 1; $c -le $NumChapters; $c++) {
    $sidebarContent += @"
    {
      type: 'autogenerated',
      dirName: 'chapter-$c', // Generate sidebar slice from docs/chapter-$c
    },
"@
}
$sidebarContent += @"
  ],
};
"@

Set-Content -Path $sidebarPath -Value $sidebarContent

Write-Host "Book structure generated in '$docsDir' and sidebar updated in '$sidebarPath'."
